apiVersion: v1
kind: PersistentVolume
metadata:
  name: with-baby-auth-pg
  labels: 
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "manual"
  hostPath: 
    path: /home/wangjun/hobby/pg_data/with-baby-auth
