apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-baby-auth
spec:
  selector:
    matchLabels:
      app: with-baby-auth
  template:
    metadata:
      labels:
        app: with-baby-auth
    spec:
      containers:
      - name: with-baby-auth
        image: with-baby-auth:v0.1
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
        ports:
        - containerPort: 8000
        volumeMounts:
          - mountPath: /app/.env
            name: config
            subPath: config
      volumes:
        - name: config
          configMap:
            name: with-baby-auth
