apiVersion: v1
kind: Service
metadata:
  name: with-baby-gateway
spec:
  type: NodePort
  selector:
    app: with-baby-gateway
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80